#!/bin/bash
printf '\e[8;45;65t'
clear
BLACK="\033[0;30m"
DARK_GRAY="\033[1;30m"
BLUE="\033[0;34m"
LIGHT_BLUE="\033[1;34m"
GREEN="\033[0;32m"
LIGHT_GREEN="\033[1;32m"
CYAN="\033[0;36m"
LIGHT_CYAN="\033[1;36m"
RED="\033[0;31m"
LIGHT_RED="\033[1;31m"
PURPLE="\033[0;35m"
LIGHT_PURPLE="\033[1;35m"
BROWN="\033[0;33m"
YELLOW="\033[0;33m"
LIGHT_GRAY="\033[0;37m"
WHITE="\033[1;37m"
NC="\033[0m"

printf "%b" "${GREEN}"
cat <<'TOPGAMERS_ASCII'
 ______
/\__  _\
\/_/\ \/   ___   _____      __      __      ___ ___      __   _ __   ____
   \ \ \  / __`\/\ '__`\  /'_ `\  /'__`\  /' __` __`\  /'__`\/\`'__\/',__\
    \ \ \/\ \L\ \ \ \L\ \/\ \L\ \/\ \L\.\_/\ \/\ \/\ \/\  __/\ \ \//\__, `\
     \ \_\ \____/\ \ ,__/\ \____ \ \__/.\_\ \_\ \_\ \_\ \____\\ \_\\/\____/
      \/_/\/___/  \ \ \/  \/___L\ \/__/\/_/\/_/\/_/\/_/\/____/ \/_/ \/___/
                   \ \_\    /\____/
                    \/_/    \_/__/
TOPGAMERS_ASCII
printf "%b" "${NC}"

echo ""
echo -e "                  ${LIGHT_PURPLE}三氢@芜湖玩家盟${NC}"
echo ""

parentPath=$( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )
cd "$parentPath"
appPath=$( find "$parentPath" -name '*.app' -maxdepth 1)
if [[ -z "$appPath" ]]
then
    echo -e "❌ ${LIGHT_RED}安装包已经损坏,请重新下载!${NC}"
    echo -e "✌️  本窗口可以关闭啦！"
else
appName=${appPath##*/}
appBashName=${appName// /\ }
appDIR="/Applications/${appBashName}"
echo -e "『${RED}${appBashName%.*} ${NC}已损坏,无法打开/来自身份不明的开发者』等问题修复工具"
echo ""
#未安装APP时提醒安装，已安装绕过公证
if [ ! -d "$appDIR" ];then
  echo -e "❌ ${LIGHT_RED}您还未安装 ${appBashName%.*}, 请先将软件拷贝到【${NC}${LIGHT_BLUE}应用程序${NC}${LIGHT_RED}】目录${NC}"
  else
  #绕过公证
  echo -e "👇 ${LIGHT_RED}请输入开机密码, 输入完成后按下回车键(输入过程中密码是看不见的)${NC}"
  sudo spctl --master-disable
  sudo spctl --global-disable
  sudo /usr/bin/xattr -rd com.apple.quarantine /Applications/"$appBashName"
  echo ""
  echo -e "😁 ${LIGHT_GREEN}修复成功！${NC}您现在可以正常运行 ${LIGHT_GREEN}${appBashName%.*} ${NC}了。"
  echo -e "🔥 三氢 GitHub 👉${LIGHT_BLUE} https://github.com/isTrih${NC}"
  echo -e "🎮 芜湖玩家盟官网 👉${LIGHT_BLUE} https://www.topgamers.com.cn/${NC}"
fi
echo ""
echo -e "✌️  操作已成功完成, 本窗口可以关闭啦！"
fi
